### ISSUE TITLE
HTML document

### ISSUE THREAD

**Issue by eye942** [Tony1023/overryde#3]
Hi Matt, Angela, and Nian,
Hopefully you guys accepted the the invite to collab... (cough...cough... Nian... Angela... cough...).

TASKS:
* Learn CSS Bootstrap or something that makes html look pretty and phone optimized
* Learn how to create a container to contain our google map in the future.
* Learn how to create buttons in HTML and CSS
* Put Google Maps container and 2 Buttons on the HTML

You guys should use github.
1. Clone your repo:
```git clone https://github.com/Tony1023/overryde.git```
2. Enter the repo
```cd overryde```
3. Connect your repo to the one online
```git push origin master```
4. Create your own branch so that development is isolated.
```git branch <your-name>```
5. Move to that branch
```git checkout <your-name>```
6. Add the branch to the internet repo
```git push origin <your-name>```
7. Code your stuff...
8. After changing something, do the add-commit cycle
```git add index.html```
```git commit -m "<Your-message-here>"```
9. Once you think you're finished
```git push```
10. When you think you're finished, ask me or Tony to merge it... Github and merging is very finicky.

**Comment by Tony1023** [comment]
Very responsible Eric
