### ISSUE TITLE
Further things to do

### ISSUE THREAD

**Issue by Tony1023** [Tony1023/overryde#8]
1. Add a origin form field, also a drop-down (autocompletion).
2. Delete (or relocate) the "Reload" button.
3. Make the origin/destination form fields support search (on press Enter).
4. Auto-relayout to mobile portrait view mode (using bootstrap).
5. Reorganize the files (or maybe not really necessary)

TBA

**Comment by eye942** [comment]
Lots of stuff. Might as well as open issues for each thing...
