### ISSUE TITLE
[Feature Request] Add Optional Origin Bar

### ISSUE THREAD

**Issue by eye942** [Tony1023/overryde#9]
Add a new option to change the origin to a custom place using the G Maps API.

Very similar to setting the destination.

**Comment by Tony1023** [comment]
[Feature Request] As if it's an industy-level project

**Comment by Tony1023** [comment]
Then our search should not be toggled by selecting from autocompletion either. We probably need a "search" button.

**Comment by Tony1023** [comment]
Done. Still need to handle the cases where no inputs are given.
